# Generated by Django 2.2.1 on 2019-05-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroi',
            name='habilidade_1',
            field=models.TextField(blank=True, max_length=500, verbose_name='Habilidade um: '),
        ),
        migrations.AddField(
            model_name='heroi',
            name='habilidade_2',
            field=models.TextField(blank=True, max_length=500, verbose_name='Habilidade dois '),
        ),
        migrations.AddField(
            model_name='heroi',
            name='habilidade_3',
            field=models.TextField(blank=True, max_length=500, verbose_name='Habilidade três: '),
        ),
        migrations.AddField(
            model_name='heroi',
            name='habilidade_4',
            field=models.TextField(blank=True, max_length=500, verbose_name='Habilidade quatro: '),
        ),
        migrations.AddField(
            model_name='heroi',
            name='habilidade_5',
            field=models.TextField(blank=True, max_length=500, verbose_name='Habilidade cinco : '),
        ),
        migrations.AddField(
            model_name='heroi',
            name='habilidade_6',
            field=models.TextField(blank=True, max_length=500, verbose_name='Habilidade seis: '),
        ),
        migrations.AddField(
            model_name='heroi',
            name='habilidade_7',
            field=models.TextField(blank=True, max_length=500, verbose_name='Habilidade sete: '),
        ),
        migrations.DeleteModel(
            name='Habilidade',
        ),
    ]
