# Generated by Django 2.2.1 on 2019-05-04 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome da função')),
                ('definiçao', models.TextField(max_length=300, verbose_name='Definição')),
            ],
        ),
        migrations.CreateModel(
            name='Heroi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=40, verbose_name='Apelido')),
                ('dificuldade', models.PositiveIntegerField(verbose_name='Dificuldade')),
                ('descricao', models.TextField(max_length=800, verbose_name='Descrição do herói')),
                ('nome_verdadeiro', models.CharField(max_length=40, verbose_name='Nome verdadeiro')),
                ('ocupacao', models.CharField(max_length=40, verbose_name='Ocupação')),
                ('base_operacoes', models.CharField(max_length=100, verbose_name='Base de operações')),
                ('afiliacao', models.CharField(max_length=40, verbose_name='Afiliação')),
                ('historia', models.TextField(max_length=2000, verbose_name='História')),
                ('qtd_habilidades', models.PositiveIntegerField(verbose_name='Quantidade de habilidades')),
                ('fk_funcao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.Funcao')),
            ],
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
                ('descricao', models.TextField(max_length=700, verbose_name='Descrição')),
                ('fk_heroi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.Heroi')),
            ],
        ),
    ]
