# Generated by Django 2.2.1 on 2019-05-15 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20190504_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroi',
            name='fk_funcao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.Funcao', verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='heroi',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='heroi'),
        ),
    ]
